In [1]:
# tf = number of repeated word in a sentence / total word in a sentence
# idf = log(total number of sentence/ no of sentence that contains the word)



In [2]:
# data set link : https://www.kaggle.com/rockinjas123/spam-ham-emails
# import
import numpy as np;
import seaborn as sb
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer

In [3]:
# import dataset
df = pd.read_csv('emails.csv')

In [4]:
df
# text is the feature and spam is the label(independent)

text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
5723  Subject: re : research and development charges...     0
5724  Subject: re : receipts from visit  jim ,  than...     0
5725  Subject: re : enron case study update  wow ! a...     0
5726  Subject: re : interest  david ,  please , call...     0
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0

[5728 rows x 2 columns]

In [5]:
df['spam'].value_counts()

0    4360
1    1368
Name: spam, dtype: int64

In [6]:
# drop the duplicate values
df.drop_duplicates(inplace = True)

In [7]:
df['spam'].value_counts()
# some duplicate ham mails were drops..count droped from 4360 to 4327

0    4327
1    1368
Name: spam, dtype: int64

In [8]:
df

text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
5723  Subject: re : research and development charges...     0
5724  Subject: re : receipts from visit  jim ,  than...     0
5725  Subject: re : enron case study update  wow ! a...     0
5726  Subject: re : interest  david ,  please , call...     0
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0

[5695 rows x 2 columns]

In [9]:
df.isnull().sum()

text    0
spam    0
dtype: int64

## Seperating the x and y from dataset 

In [10]:
x = df.text.values
y = df.spam.values

In [11]:
y

array([1, 1, 1, ..., 0, 0, 0], dtype=int64)

## split dataset for training

In [12]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size = 0.2)

In [13]:
xtrain

array(["Subject: re : approval for paulo issler  anita ,  good decision .  vince  anita dupont @ enron  02 / 23 / 2001 12 : 13 pm  to : shirley crenshaw / hou / ect @ ect  cc : vince j kaminski / hou / ect @ ect  subject : re : approval for paulo issler  fyi : carolyn needed approval today for charges relating to paulo ' s green  card process . mike was the only vp here today so i asked him to approve  them . hope that was alright . anita  - - - - - - - - - - - - - - - - - - - - - - forwarded by anita dupont / na / enron on 02 / 23 / 2001 12 : 06  pm - - - - - - - - - - - - - - - - - - - - - - - - - - -  mike a roberts @ ect  02 / 23 / 2001 11 : 04 am  to : carolyn wedel / enron @ enronxgate @ enron  cc : anita dupont / na / enron @ enron  subject : re : approval for paulo issler  carolyn ,  approval to post the attached charges for paulo issler is granted .  mike roberts  v . p . research",
       'Subject: 4 - urgent - owa please print this now .  current notes user :  reasons for us

In [14]:
ytrain

array([0, 0, 1, ..., 1, 0, 0], dtype=int64)

# Data preprocessing

In [15]:
cv = CountVectorizer()
x_train = cv.fit_transform(xtrain)

In [16]:
x_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

# ML model

In [17]:
from sklearn.naive_bayes import MultinomialNB
#MultinomialNB is best suite for text based workd

In [18]:
model = MultinomialNB()
model.fit(x_train,ytrain)

MultinomialNB()

In [19]:
x_test = cv.transform(xtest)

In [20]:
x_test.toarray()

array([[ 0,  0,  0, ...,  0,  0,  0],
       [53,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       ...,
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 3,  0,  0, ...,  0,  0,  0]], dtype=int64)

In [21]:
# model accuracy
model.score(x_test,ytest)

0.9885864793678666

In [22]:
emails = ['I am looking for ML bengali tutorial', 'You have won a Iphone. Now fill up this adress form']

In [23]:
cv_emails = cv.transform(emails)


In [24]:
cv_emails

<2x33182 sparse matrix of type '<class 'numpy.int64'>'
	with 14 stored elements in Compressed Sparse Row format>

In [25]:
model.predict(cv_emails)
# here the output 0 means not a ham mail and 1 means it is a spam mail

array([0, 1], dtype=int64)

## Performace matrix

In [26]:
pred = model.predict(x_test)

In [27]:
pred

array([1, 0, 0, ..., 0, 1, 0], dtype=int64)

In [28]:
from sklearn.metrics import accuracy_score

In [29]:
# compare trained and test dataset
accuracy_score(ytest,pred)

0.9885864793678666

## Generate confusion matrix

In [30]:
from sklearn.metrics import confusion_matrix

In [31]:
# compare trained and test dataset
confusion_matrix(ytest,pred)

array([[878,   9],
       [  4, 248]], dtype=int64)

## classification report

In [32]:
from sklearn.metrics import classification_report

In [33]:
print(classification_report(ytest,pred))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99       887
           1       0.96      0.98      0.97       252

    accuracy                           0.99      1139
   macro avg       0.98      0.99      0.98      1139
weighted avg       0.99      0.99      0.99      1139



# K Fold cross validation

In [34]:
from sklearn.model_selection import cross_val_score

In [44]:
# must do data preprocessing beacuse kfold can't have text based data as a input parameter.So convert that into numeric data
cv2 = CountVectorizer()
x_train2 = cv2.fit_transform(x)


In [41]:
cv_score = cross_val_score(model,x_train2,y,cv=10)

In [42]:
cv_score

array([0.98421053, 0.99122807, 0.98947368, 0.99122807, 0.99649123,
       0.98418278, 0.98242531, 0.99297012, 0.98945518, 0.99121265])

In [46]:
cv_score.mean()

0.989287762464157