In [1]:
# tf = number of repeated word in a sentence / total word in a sentence
# idf = log(total number of sentence/ no of sentence that contains the word)



In [27]:
# data set link : https://www.kaggle.com/rockinjas123/spam-ham-emails
# import
import numpy as np;
import seaborn as sb
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer

In [28]:
# import dataset
df = pd.read_csv('emails.csv')

In [4]:
df
# text is the feature and spam is the label(independent)

text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
5723  Subject: re : research and development charges...     0
5724  Subject: re : receipts from visit  jim ,  than...     0
5725  Subject: re : enron case study update  wow ! a...     0
5726  Subject: re : interest  david ,  please , call...     0
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0

[5728 rows x 2 columns]

In [5]:
df['spam'].value_counts()

0    4360
1    1368
Name: spam, dtype: int64

In [6]:
# drop the duplicate values
df.drop_duplicates(inplace = True)

In [7]:
df['spam'].value_counts()
# some duplicate ham mails were drops..count droped from 4360 to 4327

0    4327
1    1368
Name: spam, dtype: int64

In [8]:
df

text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
5723  Subject: re : research and development charges...     0
5724  Subject: re : receipts from visit  jim ,  than...     0
5725  Subject: re : enron case study update  wow ! a...     0
5726  Subject: re : interest  david ,  please , call...     0
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0

[5695 rows x 2 columns]

In [9]:
df.isnull().sum()

text    0
spam    0
dtype: int64

## Seperating the x and y from dataset 

In [10]:
x = df.text.values
y = df.spam.values

In [11]:
y

array([1, 1, 1, ..., 0, 0, 0], dtype=int64)

## split dataset for training

In [12]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size = 0.2)

In [13]:
xtrain

array(['Subject: ameriflash newsletter  michell vitrella called and wanted to know if the " research group " would  like to submit an article for the next issue of the ena newsletter  ( " ameriflash )  they need to have the article by tomorrow .  thanks !  shirley  - - - - - - - - - - - - - - - - - - - - - - forwarded by shirley crenshaw / hou / ect on 10 / 24 / 2000  10 : 15 am - - - - - - - - - - - - - - - - - - - - - - - - - - -  from : michelle vitrella 10 / 24 / 2000 09 : 53 am  to : shirley crenshaw / hou / ect @ ect  cc :  subject : ameriflash newsletter  - - - - - - - - - - - - - - - - - - - - - - forwarded by michelle vitrella / hou / ect on 10 / 24 / 2000  09 : 54 pm - - - - - - - - - - - - - - - - - - - - - - - - - - -  enron north america corp .  from : ena public relations @ enron 10 / 19 / 2000  08 : 25 pm  sent by : enron announcements @ enron  to : all _ ena _ egm _ eim  cc :  subject : ameriflash newsletter  note from mark frevert  with the wide and varied activities o

In [14]:
ytrain

array([0, 0, 0, ..., 1, 0, 0], dtype=int64)

# Data preprocessing

In [15]:
cv = CountVectorizer()
x_train = cv.fit_transform(xtrain)

In [16]:
x_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [2, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [2, 0, 0, ..., 0, 0, 0]], dtype=int64)

# ML model

In [17]:
from sklearn.naive_bayes import MultinomialNB
#MultinomialNB is best suite for text based workd

In [18]:
model = MultinomialNB()
model.fit(x_train,ytrain)

MultinomialNB()

In [19]:
x_test = cv.transform(xtest)

In [20]:
x_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0]], dtype=int64)

In [21]:
# model accuracy
model.score(x_test,ytest)

0.9920983318700615

In [22]:
emails = ['I am looking for ML bengali tutorial', 'You have won a Iphone. Now fill up this adress form']

In [23]:
cv_emails = cv.transform(emails)


In [24]:
cv_emails

<2x33943 sparse matrix of type '<class 'numpy.int64'>'
	with 14 stored elements in Compressed Sparse Row format>

In [25]:
model.predict(cv_emails)
# here the output 0 means not a ham mail and 1 means it is a spam mail

array([0, 1], dtype=int64)

## Performace matrix

In [26]:
pred = model.predict(x_test)

In [29]:
pred

array([0, 0, 1, ..., 0, 1, 0], dtype=int64)

In [31]:
from sklearn.metrics import accuracy_score

In [33]:
# compare trained and test dataset
accuracy_score(ytest,pred)

0.9920983318700615

## Generate confusion matrix

In [35]:
from sklearn.metrics import confusion_matrix

In [36]:
# compare trained and test dataset
confusion_matrix(ytest,pred)

array([[889,   1],
       [  8, 241]], dtype=int64)

## classification report

In [37]:
from sklearn.metrics import classification_report

In [38]:
classification_report(ytest,pred)

'              precision    recall  f1-score   support\n\n           0       0.99      1.00      0.99       890\n           1       1.00      0.97      0.98       249\n\n    accuracy                           0.99      1139\n   macro avg       0.99      0.98      0.99      1139\nweighted avg       0.99      0.99      0.99      1139\n'