In [ ]:
# tf = number of repeated word in a sentence / total word in a sentence
# idf = log(total number of sentence/ no of sentence that contains the word)



In [30]:
# data set link : https://www.kaggle.com/rockinjas123/spam-ham-emails
# import
import numpy as np;
import seaborn as sb
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer

In [3]:
# import dataset
df = pd.read_csv('emails.csv')

In [4]:
df
# text is the feature and spam is the label(independent)

text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
5723  Subject: re : research and development charges...     0
5724  Subject: re : receipts from visit  jim ,  than...     0
5725  Subject: re : enron case study update  wow ! a...     0
5726  Subject: re : interest  david ,  please , call...     0
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0

[5728 rows x 2 columns]

In [5]:
df['spam'].value_counts()

0    4360
1    1368
Name: spam, dtype: int64

In [6]:
# drop the duplicate values
df.drop_duplicates(inplace = True)

In [8]:
df['spam'].value_counts()
# some duplicate ham mails were drops..count droped from 4360 to 4327

0    4327
1    1368
Name: spam, dtype: int64

In [9]:
df

text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
5723  Subject: re : research and development charges...     0
5724  Subject: re : receipts from visit  jim ,  than...     0
5725  Subject: re : enron case study update  wow ! a...     0
5726  Subject: re : interest  david ,  please , call...     0
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0

[5695 rows x 2 columns]

In [10]:
df.isnull().sum()

text    0
spam    0
dtype: int64

## Seperating the x and y from dataset 

In [11]:
x = df.text.values
y = df.spam.values

In [15]:
y

array([1, 1, 1, ..., 0, 0, 0], dtype=int64)

## split dataset for training

In [45]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size = 0.2)

In [34]:
xtrain

array(['Subject: fyi - a new esai report forecasting power prices in eastern markets  attached is a new report forecasting jan - feb - mar power prices based on  weather services international weather forecasts and esai energy analytics .  feel free to comment . a version using national weather service information  will also be available .  ed  edward n . krapels , phd  managing director  esai power and gas services  tel 781 245 2036  cell 617 899 4948  ekrapels @ esaibos . com  www . esai . com  - esai energycast power dec 00 . pdf',
       'Subject: new 22 cpm color copier information  kevin ,  i am not sure by what date you require a color copier but if you can wait  until april , lanier has let me know that they are going to release their new  22 copy per minute color copier @ that time . please look @ the attached  spreadsheet and compare the cost with the $ 24 cpm canon copier sent to you  on 01 / 31 / 2000 :  let me know what you think .  thanks , iain . . . . . . . . . . . . . 

In [46]:
ytrain

array([0, 0, 0, ..., 1, 0, 0], dtype=int64)

# Data preprocessing

In [47]:
cv = CountVectorizer()
x_train = cv.fit_transform(xtrain)

In [48]:
x_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

# ML model

In [40]:
from sklearn.naive_bayes import MultinomialNB
#MultinomialNB is best suite for text based workd

In [49]:
model = MultinomialNB()
model.fit(x_train,ytrain)

MultinomialNB()

In [50]:
x_test = cv.transform(xtest)

In [52]:
x_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [54]:
# model accuracy
model.score(x_test,ytest)

0.9885864793678666

In [64]:
emails = ['I am looking for ML bengali tutorial', 'You have won a Iphone. Now fill up this adress form']

In [65]:
cv_emails = cv.transform(emails)


In [66]:
cv_emails

<2x33298 sparse matrix of type '<class 'numpy.int64'>'
	with 14 stored elements in Compressed Sparse Row format>

In [68]:
model.predict(cv_emails)
# here the output 0 means not a ham mail and 1 means it is a spam mail

array([0, 1], dtype=int64)